'use client';
import HorizontalNavbar from '@/components/HorizontalNavbar';

import Sidebar from '@/components/Sidebar';
import BottomNavbar from '@/components/BottomNavbar';
import './globals.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '700'],
});
const metadata: Metadata = {
  title: 'Md Faiz Portfolio',
  description: 'Generated by create next app, tailwind css, shadcn ui and Framer Motion.',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Md Faiz Portfolio</title>
        <meta name="description" content="Md Faiz portfolio created by NextJS, Tailwind CSS, Shadcn UI and Framer Motion."></meta>
        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"></link>
      </head>
      <body className={poppins.className}>
        <main className="relative  md:container md:mx-auto mx-2">
          <HorizontalNavbar />

          <div className="lg:flex my-4 lg:gap-10">
            <div className="hidden lg:block">
              <Sidebar />
            </div>

            <div className=" flex-grow  pb-32 mt-12 lg:mt-0">{children}</div>
          </div>
          <div className="hidden dark:block -z-[100] absolute w-[100%] inset-0 gradient-02" />
          <div className="lg:hidden">
            <BottomNavbar />
          </div>
        </main>
      </body>
    </html>
  );
}
